# typed: false
# frozen_string_literal: true

# Homebrew formula for Nimbus (headless gateway + CLI).
# Generated by scripts/release/package-manager-manifests.ts — do not edit by hand.
class Nimbus < Formula
  desc "Local-first AI agent framework (headless gateway + CLI)"
  homepage "https://github.com/nimbus-agent/Nimbus"
  version "2.7.1"
  license "AGPL-3.0-only"

  on_macos do
    on_arm do
      url "https://github.com/nimbus-agent/Nimbus/releases/download/v2.7.1/nimbus-headless-macos-arm64.tar.gz"
      sha256 "4266ea24785fe4238d78ad50854f9a7cc4f66d13cf17e5b1ca6acb60b1258709"
    end
    on_intel do
      url "https://github.com/nimbus-agent/Nimbus/releases/download/v2.7.1/nimbus-headless-macos-x64.tar.gz"
      sha256 "8c59593e8707322cf5f34e03f74f64a8366b7ff0b77e480334b9f7f46b3eff00"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nimbus-agent/Nimbus/releases/download/v2.7.1/nimbus-headless-linux-amd64-v2.7.1.tar.gz"
      sha256 "7eba80f7de2499634735e6c8348cd1650d381f4ae2f51954d2e6700620d2baa4"
    end
  end

  def install
    bin.install "nimbus"
    bin.install "nimbus-gateway"
  end

  test do
    assert_match "2.7.1", shell_output("#{bin}/nimbus --version")
  end
end
